// <auto-generated />
using System;
using System.Collections.Generic;
using Blazeditor.Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blazeditor.Application.Data.Migrations
{
    [DbContext(typeof(BlazeditorDbContext))]
    partial class BlazeditorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AreaTilePalette", b =>
                {
                    b.Property<Guid>("AreasId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TilePalettesId")
                        .HasColumnType("uuid");

                    b.HasKey("AreasId", "TilePalettesId");

                    b.HasIndex("TilePalettesId");

                    b.ToTable("AreaTilePalettes", (string)null);
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CellSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Size", "Blazeditor.Application.Data.Entities.Area.Size#Size", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.ToTable("Areas");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Definition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Definitions");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Portal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("DestinationAreaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationAreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Destination", "Blazeditor.Application.Data.Entities.Portal.Destination#Coordinate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Layer")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Location", "Blazeditor.Application.Data.Entities.Portal.Location#Coordinate", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Layer")
                                .HasColumnType("integer");

                            b1.Property<int>("X")
                                .HasColumnType("integer");

                            b1.Property<int>("Y")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.HasIndex("DestinationAreaId");

                    b.HasIndex("LocationAreaId");

                    b.ToTable("Portals");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Tile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<Guid>("TilePaletteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FloorProperties", "Blazeditor.Application.Data.Entities.Tile.FloorProperties#FloorProperties", b1 =>
                        {
                            b1.Property<float>("Impedance")
                                .HasColumnType("real");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "ShimProperties", "Blazeditor.Application.Data.Entities.Tile.ShimProperties#ShimProperties", b1 =>
                        {
                            b1.Property<int>("ShimType")
                                .HasColumnType("integer");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Size", "Blazeditor.Application.Data.Entities.Tile.Size#Size", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("TilePaletteId");

                    b.ToTable("Tiles");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.TileMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("Layer")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TilePlacements")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Size", "Blazeditor.Application.Data.Entities.TileMap.Size#Size", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Height")
                                .HasColumnType("integer");

                            b1.Property<int>("Width")
                                .HasColumnType("integer");
                        });

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.ToTable("TileMaps");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.TilePalette", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CellSize")
                        .HasColumnType("integer");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId");

                    b.ToTable("TilePalettes");
                });

            modelBuilder.Entity("AreaTilePalette", b =>
                {
                    b.HasOne("Blazeditor.Application.Data.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("AreasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blazeditor.Application.Data.Entities.TilePalette", null)
                        .WithMany()
                        .HasForeignKey("TilePalettesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Area", b =>
                {
                    b.HasOne("Blazeditor.Application.Data.Entities.Definition", "Definition")
                        .WithMany("Areas")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Portal", b =>
                {
                    b.HasOne("Blazeditor.Application.Data.Entities.Definition", "Definition")
                        .WithMany("Portals")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blazeditor.Application.Data.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("DestinationAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Blazeditor.Application.Data.Entities.Area", null)
                        .WithMany()
                        .HasForeignKey("LocationAreaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Tile", b =>
                {
                    b.HasOne("Blazeditor.Application.Data.Entities.TilePalette", "TilePalette")
                        .WithMany("Tiles")
                        .HasForeignKey("TilePaletteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TilePalette");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.TileMap", b =>
                {
                    b.HasOne("Blazeditor.Application.Data.Entities.Area", "Area")
                        .WithMany("TileMaps")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.TilePalette", b =>
                {
                    b.HasOne("Blazeditor.Application.Data.Entities.Definition", "Definition")
                        .WithMany("TilePalettes")
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Area", b =>
                {
                    b.Navigation("TileMaps");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.Definition", b =>
                {
                    b.Navigation("Areas");

                    b.Navigation("Portals");

                    b.Navigation("TilePalettes");
                });

            modelBuilder.Entity("Blazeditor.Application.Data.Entities.TilePalette", b =>
                {
                    b.Navigation("Tiles");
                });
#pragma warning restore 612, 618
        }
    }
}
